# **Avenging the Ancestors Coalition (ATAC) July 4 Gathering Website & Playlist**

On January 22, 2026 the Trump Administration removed the original panels of the President's House / Slavery Memorial in Philadelphia, as part of the Executive Order “Restoring Truth and Sanity to American History". The Trump Administration then replaced the originals with dishonest & dulled versions of their own. 

The Avenging the Ancestors Coalition (ATAC) has been leading a legal campaign to have the original panels restored. ATAC is a "Philadelphia-based organization of African American historians, attorneys, concerned citizens, elected officials, religious leaders, media personalitites, community activists, and registered voters." They were founded in 2002 to push the creation of the Slavery Memorial, which "honors primarily the nine African descendants enslaved by President George Washington at the President's House."

ATAC held a gathering on July 4, 2026 to further honor the descendents and provide an update on their progress in the legal battle. 

Read more about the situation here: https://www.avengingtheancestors.com/

### **YOUR PROJECT:**

* Use Python to build a *playlist database* for the July 4 Gathering
* Format the playlist to be published on a promotional website - https://techcore2-tc2.github.io/Capstone_HQ_Afternoon_Summer26/atac_gathering/
* *Skills Needed*: lists, if/else conditionals, for-loops, functions

![image](../atac_gathering/july4_gathering.jpg)

-----
# **TASK 1: MAKE A LIST (OF LISTS) OF SONGS** 
--  
  
We'll start by making individual lists for each song following the format below:

```python 
songX = ['song title', 'artist', 'embeded YouTube link', number of views, year released, Explicit (True or False)]
```

#### IMPORTANT NOTES
* to find the embeded YouTube link: open the video, click *Share*, then *Embed* and select the link in quotations following src=
* write the number of views as an *Integer*. For example, for 640K, write 640000
* if the song contains profanity or mature visual content, write True for the Explicit value, False if not 

--  

### 1a)
Following the examples, make lists for 5 songs to be included at the gathering

In [1]:
''' 1a) LISTS OF SONGS '''

# example songs
song1 = ['The Field', 'Blood Orange', 'https://www.youtube.com/embed/yTaz0TB9Zco?si=jUT7iM6EdyZHr-u3', 604906, 2025, False]
song2 = ['Stupid Prizes', 'redveil', 'https://www.youtube.com/embed/dj5nZsQ3p2o?si=gUrrDWxD-Bk3yThe', 4400, 2025, True]
song3 = ['Girl, Get Up', 'Doechii, SZA', 'https://www.youtube.com/embed/jBKJbedSrA0?si=R2lDU0OMZmacY3tY', 5100000, 2025, True]
song4 = ['Walking Shoes', 'Mali Music', 'https://www.youtube.com/embed/1dexBLGQGSs?si=waNMbE0CHv9s_UeO', 1200000, 2014,  False]
song5 = ['Yoga', 'Janelle Monae', 'https://www.youtube.com/embed/0OkB6p_FZAw?si=zMs0gzWyAUTZLrEM"', 83000000, 2015,  True]

# Abdou
song6 =['Starboy','The Weeknd','https://www.youtube.com/embed/Rif-RTvmmss?si=wAMCc-f7WT7rkNNR', 90031660,2023,True]
song7 =['NINAO','Gims','https://www.youtube.com/embed/VT2qF97pQNw?si=hkmYaYCt_N0uwwI2',256000000,2025,False]
song8 =['Timeless','The weeknd & playboi carti','https://www.youtube.com/embed/5EpyN_6dqyk?si=_vUSyJSy7Gfz1a97',263000000,2025,False] 
song9 =['The bigger picture','lil baby','https://www.youtube.com/embed/_VDGysJGNoI?si=KnGMjHqf-itXkZ7g',212000000,2020,False]
song10 =['Blinding lights','The weeknd','https://www.youtube.com/embed/4NRXx6U8ABQ?si=KK2ADcxvoiLupeIL',1000000000,2020,False]

# Aminatou
song11 = ['Diamonds', 'Rihanna', 'https://www.youtube.com/embed/4mVo93E9wpU', 2500000000, 2012, False]
song12 = ['Kill Bill', 'SZA', 'https://www.youtube.com/embed/lcX37Pzobxw', 450000000, 2022, True]
song13 = ['CUFF IT', 'Beyoncé', 'https://www.youtube.com/embed/v9o49zO2FfU', 180000000, 2022, True]
song14 = ['Blinding Lights', 'The Weeknd', 'https://www.youtube.com/embed/4NRXx6U8ABQ', 800000000, 2019, False]
song15 = ['HUMBLE.', 'Kendrick Lamar', 'https://www.youtube.com/embed/tvTRZJ-4EyI', 920000000, 2017, True]

# Amir
song16 =['Fire Flies', 'Owl City', 'https://www.youtube.com/embed/psuRGfAaju4', 629000000, 2009, False]
song17 =['So Sick', 'Ne-Yo', 'https://www.youtube.com/embed/IxszlJppRQI', 496000000, 2009, False]
song18 =['Counting Stars', 'OneRepublic', 'https://www.youtube.com/embed/hT_nvWreIhg', 4400000000, 2013, False]
song19 =['Flagpole Sitta', 'Harvey Danger', 'https://www.youtube.com/embed/wYsMjEeEg4g?si=JnazjWUphOR8i6CV', 12000000, 2014, False]
song20 =['Riptide', 'Vance Joy', 'https://www.youtube.com/embed/uJ_1HMAGb4k?si=lpTOfTPMyn7Hn1HK', 739000000, 2013, False]

# Cabre
song21 = ['Dreams and Nightmares', 'Meek Mill', 'https://www.youtube.com/embed/S43S_eMvC-8', 450000000, 2012, True]
song22 = ['Real YN', 'Drake', 'https://www.youtube.com/embed/Lilspazz9_RealYN', 677000, 2023, False]
song23 = ['Drip Too Hard', 'Lil Baby', 'https://www.youtube.com/embed/uTRJ-S66m6g', 1200000000, 2018, True]
song24 = ['Nights', 'Frank Ocean', 'https://www.youtube.com/embed/r4l9bFqgMaQ', 350000000, 2016, True]
song25 =  ['PARTYNEXTDOOR', 'PARTYNEXTDOOR', 'https://www.youtube.com/embed/example', 150000000, 2020, True]

# Caiden
song26 =['20 Plus', 'Lilspazz9', 'https://www.youtube.com/embed/n3-QbOpwEIY?si=9H8EQiqrNfqfBrxn', 1987178, 2025, True]
song27 =['Vultures', 'FullyChop', 'https://www.youtube.com/embed/FdzPyCJpl_A?si=E0jZqKfHUyAIty6j', 1128409, 2026, True]
song28 =['Ian mean it shot by drevegas', 'imsomarcus', 'https://www.youtube.com/embed/ILNT1ZYr3oE?si=iu38ILi45FNnT8av', 16901, 2025, True]
song29 =["While We're Young", 'Jhené Aiko', 'https://www.youtube.com/embed/LjvwRSKVQNs?si=ulvauqMsxdnjWzIF', 106554052, 2017, True]

# Elijah
song50 =['Workin Day and Night', 'Michael Jackson', 'https://www.youtube.com/embed/MWnyCxva6bA?si=xKN1KAaynTbEoP3', 22227316, 1979, False]
song51 =['I Wonder', 'Kanye West', 'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l', 165596492, 2007, True]
song52 =['Goodbye to Love', 'Carpenters', 'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l', 2572645, 1972, False]
song53 =['I Will Survive', 'Gloria Gaynor', 'https://www.youtube.com/embed/6dYWe1c3OyU?si=CSVmWbAgI1w-1A2r', 186956675, 1978, False]
song54 =['In the Air Tonight', 'Phil Collins', 'https://www.youtube.com/embed/YkADj0TPrJA?si=u5dI2lLLax2zRy9i', 343028265, 1981, True]

# Hawa
song30 =['LOYALTY', 'Kendrick Lamar', 'https://www.youtube.com/embed/sN8H2ypmzlA?si=wYFaQDitA-_Heo24', 1763334, 2018, True]
song31 =['KiLLKiSS', 'Ave Mujica', 'https://www.youtube.com/embed/RexyoaXaQ1o?si=wyHbFJSAVq17t-8w', 6923624, 2025, False]
song32 =['TWICE"Talk that Talk" M/V', 'TWICE','https://www.youtube.com/embed/k6jqx9kZgPM?si=X1Qex5-l4-Ax115d',219590569, 2022, False]
song33 =['NewJeans (뉴진스) ‘Supernatural’ Official MV (Part.1)', 'HYBE LABELS','https://www.youtube.com/embed/ZncbtRo7RXs?si=Irgcwdn0BS1n-TUu' , 95814355, 2024, False]
song34 =['Treason','Tinashe','https://www.youtube.com/embed/m4eVGPN-ZLc?si=3yjcH3yutKxKk9ZG', 556051, 2023, True]

# Houraye
song35 =['In For It', 'Tory Lanez', 'https://youtu.be/Amp86v4Nd8Q?si=580Spuf4zjCn2G5S', 59528124, 2018, True]
song36 =['Selfish', 'PnB Rock', '"https://www.youtube.com/embed/u4XyXLQxQbQ?si=ESTBlaXkEa_DGBlu"', 77539193, 2016, True]
song37 =['Cinderella', 'Mac Miller feat Ty Dolla $ign', '"https://www.youtube.com/embed/0fcsGS1dEro?si=_o3cZrrSGLD596Vk"', 36500649, 2016, True]
song38 =['Teyana', 'Tory Lanez', '"https://www.youtube.com/embed/u7v8yEUPilU?si=8qE3xwd66EcxdHVO"', 2171483, 2014, True]
song39 =['All I Need', 'Lloyd', 'https://youtu.be/15zse5jbU-Q?si=0VnVhlRYG8F14FZW', 8759201, 2014, True]

# Jenna
song40 =['Put Your Records On', 'Ritt Momney', 'https://www.youtube.com/embed/u7Mf_ZjI2Pg?si=Vyaw-_s1ppGMlV0d', 20994428, 2020, False]
song41 =['Siren', 'Kailee Morgue', 'https://youtu.be/WKWG4zCALoE?si=dDUoXgaku-U9Mc5H', 9322877, 2018, False]
song42 =['MUTT', 'Leon Thomas, Chris Brown', 'https://youtu.be/ueLrb3-oVpY?si=quU91VILvgQtsfZe', 21200039, 2025, False]
song43 =['Mmm Yeah', 'Austin Mahone, Pitpull', 'https://youtu.be/MMAppa1cAVo?si=0aer88WtD37Mjo-P', 257648083, 2014, False]
song44 =['Cognac Queen','Megan Thee Stallion', 'https://youtu.be/GGwVkl56DNo?si=VqWIvEehaP2V_N6l', 32036350, 2022, True]

# Mamadou
song45 =['Geeked', 'Lucki', 'https://www.youtube.com/embed/-UO9xzsnPKw?si=gGGXoDPqx4C2y5nY', 4200000, 2019, True]
song46 =['Sunset', 'Lucki', 'https://www.youtube.com/embed/4-pdlpEwMao?si=tNa9_uhxkls_jnR3', 7000000, 2025, True]
song47 =['Randomly', 'Lucki', 'https://www.youtube.com/embed/-UO9xzsnPKw?si=nRVg_Uuaw3A9TUkN', 8000000, 2023, True]
song48 =['LUV', 'Tory Lanez', 'https://www.youtube.com/embed/P9rFeGAdX0A?si=5oJNsXL8rdNXaYA2', 275815687,2016, False]
song49 =['Nothing like uuuuu', 'Nettspend', 'https://www.youtube.com/embed/2cp_UrFXl0w?si=3dEdpaRIHNJ_2vfe', 1000000, 2024, True ]

### 1b)
Now let's make a *list of lists (LoL)* of your songs. This will help us create the playlist later and make additional changes.

In [2]:
''' 1b) LIST OF LISTS '''

# FILL IN CODE BELOW
song_list = [song1, song2, song3, song4, song5, song6, song7, song8, song9, song11, song12,
             song13, song14, song15, song16, song17, song18, song19, song20, song21, song22, song23,
             song24, song25, song26, song27, song28, song29, song30, song31, song32, song33, song34,
             song35, song36, song37, song38, song39, song40, song41, song42, song43, song44, song45,
             song46, song47, song48, song49, song50, song51, song52, song53, song54]
display(song_list)

[['The Field',
  'Blood Orange',
  'https://www.youtube.com/embed/yTaz0TB9Zco?si=jUT7iM6EdyZHr-u3',
  604906,
  2025,
  False],
 ['Stupid Prizes',
  'redveil',
  'https://www.youtube.com/embed/dj5nZsQ3p2o?si=gUrrDWxD-Bk3yThe',
  4400,
  2025,
  True],
 ['Girl, Get Up',
  'Doechii, SZA',
  'https://www.youtube.com/embed/jBKJbedSrA0?si=R2lDU0OMZmacY3tY',
  5100000,
  2025,
  True],
 ['Walking Shoes',
  'Mali Music',
  'https://www.youtube.com/embed/1dexBLGQGSs?si=waNMbE0CHv9s_UeO',
  1200000,
  2014,
  False],
 ['Yoga',
  'Janelle Monae',
  'https://www.youtube.com/embed/0OkB6p_FZAw?si=zMs0gzWyAUTZLrEM"',
  83000000,
  2015,
  True],
 ['Starboy',
  'The Weeknd',
  'https://www.youtube.com/embed/Rif-RTvmmss?si=wAMCc-f7WT7rkNNR',
  90031660,
  2023,
  True],
 ['NINAO',
  'Gims',
  'https://www.youtube.com/embed/VT2qF97pQNw?si=hkmYaYCt_N0uwwI2',
  256000000,
  2025,
  False],
 ['Timeless',
  'The weeknd & playboi carti',
  'https://www.youtube.com/embed/5EpyN_6dqyk?si=_vUSyJSy7Gfz1a97',
  263000000,
  2025,
  False],
 ['The bigger picture',
  'lil baby',
  'https://www.youtube.com/embed/_VDGysJGNoI?si=KnGMjHqf-itXkZ7g',
  212000000,
  2020,
  False],
 ['Diamonds',
  'Rihanna',
  'https://www.youtube.com/embed/4mVo93E9wpU',
  2500000000,
  2012,
  False],
 ['Kill Bill',
  'SZA',
  'https://www.youtube.com/embed/lcX37Pzobxw',
  450000000,
  2022,
  True],
 ['CUFF IT',
  'Beyoncé',
  'https://www.youtube.com/embed/v9o49zO2FfU',
  180000000,
  2022,
  True],
 ['Blinding Lights',
  'The Weeknd',
  'https://www.youtube.com/embed/4NRXx6U8ABQ',
  800000000,
  2019,
  False],
 ['HUMBLE.',
  'Kendrick Lamar',
  'https://www.youtube.com/embed/tvTRZJ-4EyI',
  920000000,
  2017,
  True],
 ['Fire Flies',
  'Owl City',
  'https://www.youtube.com/embed/psuRGfAaju4',
  629000000,
  2009,
  False],
 ['So Sick',
  'Ne-Yo',
  'https://www.youtube.com/embed/IxszlJppRQI',
  496000000,
  2009,
  False],
 ['Counting Stars',
  'OneRepublic',
  'https://www.youtube.com/embed/hT_nvWreIhg',
  4400000000,
  2013,
  False],
 ['Flagpole Sitta',
  'Harvey Danger',
  'https://www.youtube.com/embed/wYsMjEeEg4g?si=JnazjWUphOR8i6CV',
  12000000,
  2014,
  False],
 ['Riptide',
  'Vance Joy',
  'https://www.youtube.com/embed/uJ_1HMAGb4k?si=lpTOfTPMyn7Hn1HK',
  739000000,
  2013,
  False],
 ['Dreams and Nightmares',
  'Meek Mill',
  'https://www.youtube.com/embed/S43S_eMvC-8',
  450000000,
  2012,
  True],
 ['Real YN',
  'Drake',
  'https://www.youtube.com/embed/Lilspazz9_RealYN',
  677000,
  2023,
  False],
 ['Drip Too Hard',
  'Lil Baby',
  'https://www.youtube.com/embed/uTRJ-S66m6g',
  1200000000,
  2018,
  True],
 ['Nights',
  'Frank Ocean',
  'https://www.youtube.com/embed/r4l9bFqgMaQ',
  350000000,
  2016,
  True],
 ['PARTYNEXTDOOR',
  'PARTYNEXTDOOR',
  'https://www.youtube.com/embed/example',
  150000000,
  2020,
  True],
 ['20 Plus',
  'Lilspazz9',
  'https://www.youtube.com/embed/n3-QbOpwEIY?si=9H8EQiqrNfqfBrxn',
  1987178,
  2025,
  True],
 ['Vultures',
  'FullyChop',
  'https://www.youtube.com/embed/FdzPyCJpl_A?si=E0jZqKfHUyAIty6j',
  1128409,
  2026,
  True],
 ['Ian mean it shot by drevegas',
  'imsomarcus',
  'https://www.youtube.com/embed/ILNT1ZYr3oE?si=iu38ILi45FNnT8av',
  16901,
  2025,
  True],
 ["While We're Young",
  'Jhené Aiko',
  'https://www.youtube.com/embed/LjvwRSKVQNs?si=ulvauqMsxdnjWzIF',
  106554052,
  2017,
  True],
 ['LOYALTY',
  'Kendrick Lamar',
  'https://www.youtube.com/embed/sN8H2ypmzlA?si=wYFaQDitA-_Heo24',
  1763334,
  2018,
  True],
 ['KiLLKiSS',
  'Ave Mujica',
  'https://www.youtube.com/embed/RexyoaXaQ1o?si=wyHbFJSAVq17t-8w',
  6923624,
  2025,
  False],
 ['TWICE"Talk that Talk" M/V',
  'TWICE',
  'https://www.youtube.com/embed/k6jqx9kZgPM?si=X1Qex5-l4-Ax115d',
  219590569,
  2022,
  False],
 ['NewJeans (뉴진스) ‘Supernatural’ Official MV (Part.1)',
  'HYBE LABELS',
  'https://www.youtube.com/embed/ZncbtRo7RXs?si=Irgcwdn0BS1n-TUu',
  95814355,
  2024,
  False],
 ['Treason',
  'Tinashe',
  'https://www.youtube.com/embed/m4eVGPN-ZLc?si=3yjcH3yutKxKk9ZG',
  556051,
  2023,
  True],
 ['In For It',
  'Tory Lanez',
  'https://youtu.be/Amp86v4Nd8Q?si=580Spuf4zjCn2G5S',
  59528124,
  2018,
  True],
 ['Selfish',
  'PnB Rock',
  '"https://www.youtube.com/embed/u4XyXLQxQbQ?si=ESTBlaXkEa_DGBlu"',
  77539193,
  2016,
  True],
 ['Cinderella',
  'Mac Miller feat Ty Dolla $ign',
  '"https://www.youtube.com/embed/0fcsGS1dEro?si=_o3cZrrSGLD596Vk"',
  36500649,
  2016,
  True],
 ['Teyana',
  'Tory Lanez',
  '"https://www.youtube.com/embed/u7v8yEUPilU?si=8qE3xwd66EcxdHVO"',
  2171483,
  2014,
  True],
 ['All I Need',
  'Lloyd',
  'https://youtu.be/15zse5jbU-Q?si=0VnVhlRYG8F14FZW',
  8759201,
  2014,
  True],
 ['Put Your Records On',
  'Ritt Momney',
  'https://www.youtube.com/embed/u7Mf_ZjI2Pg?si=Vyaw-_s1ppGMlV0d',
  20994428,
  2020,
  False],
 ['Siren',
  'Kailee Morgue',
  'https://youtu.be/WKWG4zCALoE?si=dDUoXgaku-U9Mc5H',
  9322877,
  2018,
  False],
 ['MUTT',
  'Leon Thomas, Chris Brown',
  'https://youtu.be/ueLrb3-oVpY?si=quU91VILvgQtsfZe',
  21200039,
  2025,
  False],
 ['Mmm Yeah',
  'Austin Mahone, Pitpull',
  'https://youtu.be/MMAppa1cAVo?si=0aer88WtD37Mjo-P',
  257648083,
  2014,
  False],
 ['Cognac Queen',
  'Megan Thee Stallion',
  'https://youtu.be/GGwVkl56DNo?si=VqWIvEehaP2V_N6l',
  32036350,
  2022,
  True],
 ['Geeked',
  'Lucki',
  'https://www.youtube.com/embed/-UO9xzsnPKw?si=gGGXoDPqx4C2y5nY',
  4200000,
  2019,
  True],
 ['Sunset',
  'Lucki',
  'https://www.youtube.com/embed/4-pdlpEwMao?si=tNa9_uhxkls_jnR3',
  7000000,
  2025,
  True],
 ['Randomly',
  'Lucki',
  'https://www.youtube.com/embed/-UO9xzsnPKw?si=nRVg_Uuaw3A9TUkN',
  8000000,
  2023,
  True],
 ['LUV',
  'Tory Lanez',
  'https://www.youtube.com/embed/P9rFeGAdX0A?si=5oJNsXL8rdNXaYA2',
  275815687,
  2016,
  False],
 ['Nothing like uuuuu',
  'Nettspend',
  'https://www.youtube.com/embed/2cp_UrFXl0w?si=3dEdpaRIHNJ_2vfe',
  1000000,
  2024,
  True],
 ['Workin Day and Night',
  'Michael Jackson',
  'https://www.youtube.com/embed/MWnyCxva6bA?si=xKN1KAaynTbEoP3',
  22227316,
  1979,
  False],
 ['I Wonder',
  'Kanye West',
  'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l',
  165596492,
  2007,
  True],
 ['Goodbye to Love',
  'Carpenters',
  'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l',
  2572645,
  1972,
  False],
 ['I Will Survive',
  'Gloria Gaynor',
  'https://www.youtube.com/embed/6dYWe1c3OyU?si=CSVmWbAgI1w-1A2r',
  186956675,
  1978,
  False],
 ['In the Air Tonight',
  'Phil Collins',
  'https://www.youtube.com/embed/YkADj0TPrJA?si=u5dI2lLLax2zRy9i',
  343028265,
  1981,
  True]]

### ***CHECKPOINT REACHED!***
Verify that your code is correct with the instructors and discuss the following questions:
* Do you know which data types were used to make the song lists?
* A regular list has one row of data, or in other words, it is *one dimension*. So how many dimensions does the list of lists have?
* Why did you choose these songs?

-----
# **TASK 2: ADD DATA TO SONGS WITH LOOPS & CONDITIONALS**

--

Two additional pieces of data need to be added to the songs:
- *Era*: A string label describing each song's era based on the year realeased. Options are "contemporary" (2015-present), "classic" (2000-2014), and "oldie" (< 2000)
- *Popularity*: A string label for each song's popularity based on streams. Options are "top hits" (> 1,000,000 ), "well known" (100,000 - 999,999), and "underground" (< 100,000)

In [3]:
''' 2) FOR-LOOP AND CONDITIONAL STATEMENTS FOR ERA / POPULARITY '''

# FILL IN CODE BELOW
for song in song_list:
    # check year to add an era label
    year = song[4]
    streams = song[3]

    if year >= 2015:
        song.append("contemporary")
    elif year >= 2000:
        song.append("classic")
    else:
        song.append("oldie")

    # check streams to add popularity label
    if streams >= 1000000:
        song.append("top hits")
    elif streams >= 100000:
        song.append("well known")
    else:
        song.append("underground")
    
    # check song to make sure it worked
    print(song)

['The Field', 'Blood Orange', 'https://www.youtube.com/embed/yTaz0TB9Zco?si=jUT7iM6EdyZHr-u3', 604906, 2025, False, 'contemporary', 'well known']
['Stupid Prizes', 'redveil', 'https://www.youtube.com/embed/dj5nZsQ3p2o?si=gUrrDWxD-Bk3yThe', 4400, 2025, True, 'contemporary', 'underground']
['Girl, Get Up', 'Doechii, SZA', 'https://www.youtube.com/embed/jBKJbedSrA0?si=R2lDU0OMZmacY3tY', 5100000, 2025, True, 'contemporary', 'top hits']
['Walking Shoes', 'Mali Music', 'https://www.youtube.com/embed/1dexBLGQGSs?si=waNMbE0CHv9s_UeO', 1200000, 2014, False, 'classic', 'top hits']
['Yoga', 'Janelle Monae', 'https://www.youtube.com/embed/0OkB6p_FZAw?si=zMs0gzWyAUTZLrEM"', 83000000, 2015, True, 'contemporary', 'top hits']
['Starboy', 'The Weeknd', 'https://www.youtube.com/embed/Rif-RTvmmss?si=wAMCc-f7WT7rkNNR', 90031660, 2023, True, 'contemporary', 'top hits']
['NINAO', 'Gims', 'https://www.youtube.com/embed/VT2qF97pQNw?si=hkmYaYCt_N0uwwI2', 256000000, 2025, False, 'contemporary', 'top hits']
['Timeless', 'The weeknd & playboi carti', 'https://www.youtube.com/embed/5EpyN_6dqyk?si=_vUSyJSy7Gfz1a97', 263000000, 2025, False, 'contemporary', 'top hits']
['The bigger picture', 'lil baby', 'https://www.youtube.com/embed/_VDGysJGNoI?si=KnGMjHqf-itXkZ7g', 212000000, 2020, False, 'contemporary', 'top hits']
['Diamonds', 'Rihanna', 'https://www.youtube.com/embed/4mVo93E9wpU', 2500000000, 2012, False, 'classic', 'top hits']
['Kill Bill', 'SZA', 'https://www.youtube.com/embed/lcX37Pzobxw', 450000000, 2022, True, 'contemporary', 'top hits']
['CUFF IT', 'Beyoncé', 'https://www.youtube.com/embed/v9o49zO2FfU', 180000000, 2022, True, 'contemporary', 'top hits']
['Blinding Lights', 'The Weeknd', 'https://www.youtube.com/embed/4NRXx6U8ABQ', 800000000, 2019, False, 'contemporary', 'top hits']
['HUMBLE.', 'Kendrick Lamar', 'https://www.youtube.com/embed/tvTRZJ-4EyI', 920000000, 2017, True, 'contemporary', 'top hits']
['Fire Flies', 'Owl City', 'https://www.youtube.com/embed/psuRGfAaju4', 629000000, 2009, False, 'classic', 'top hits']
['So Sick', 'Ne-Yo', 'https://www.youtube.com/embed/IxszlJppRQI', 496000000, 2009, False, 'classic', 'top hits']
['Counting Stars', 'OneRepublic', 'https://www.youtube.com/embed/hT_nvWreIhg', 4400000000, 2013, False, 'classic', 'top hits']
['Flagpole Sitta', 'Harvey Danger', 'https://www.youtube.com/embed/wYsMjEeEg4g?si=JnazjWUphOR8i6CV', 12000000, 2014, False, 'classic', 'top hits']
['Riptide', 'Vance Joy', 'https://www.youtube.com/embed/uJ_1HMAGb4k?si=lpTOfTPMyn7Hn1HK', 739000000, 2013, False, 'classic', 'top hits']
['Dreams and Nightmares', 'Meek Mill', 'https://www.youtube.com/embed/S43S_eMvC-8', 450000000, 2012, True, 'classic', 'top hits']
['Real YN', 'Drake', 'https://www.youtube.com/embed/Lilspazz9_RealYN', 677000, 2023, False, 'contemporary', 'well known']
['Drip Too Hard', 'Lil Baby', 'https://www.youtube.com/embed/uTRJ-S66m6g', 1200000000, 2018, True, 'contemporary', 'top hits']
['Nights', 'Frank Ocean', 'https://www.youtube.com/embed/r4l9bFqgMaQ', 350000000, 2016, True, 'contemporary', 'top hits']
['PARTYNEXTDOOR', 'PARTYNEXTDOOR', 'https://www.youtube.com/embed/example', 150000000, 2020, True, 'contemporary', 'top hits']
['20 Plus', 'Lilspazz9', 'https://www.youtube.com/embed/n3-QbOpwEIY?si=9H8EQiqrNfqfBrxn', 1987178, 2025, True, 'contemporary', 'top hits']
['Vultures', 'FullyChop', 'https://www.youtube.com/embed/FdzPyCJpl_A?si=E0jZqKfHUyAIty6j', 1128409, 2026, True, 'contemporary', 'top hits']
['Ian mean it shot by drevegas', 'imsomarcus', 'https://www.youtube.com/embed/ILNT1ZYr3oE?si=iu38ILi45FNnT8av', 16901, 2025, True, 'contemporary', 'underground']
["While We're Young", 'Jhené Aiko', 'https://www.youtube.com/embed/LjvwRSKVQNs?si=ulvauqMsxdnjWzIF', 106554052, 2017, True, 'contemporary', 'top hits']
['LOYALTY', 'Kendrick Lamar', 'https://www.youtube.com/embed/sN8H2ypmzlA?si=wYFaQDitA-_Heo24', 1763334, 2018, True, 'contemporary', 'top hits']
['KiLLKiSS', 'Ave Mujica', 'https://www.youtube.com/embed/RexyoaXaQ1o?si=wyHbFJSAVq17t-8w', 6923624, 2025, False, 'contemporary', 'top hits']
['TWICE"Talk that Talk" M/V', 'TWICE', 'https://www.youtube.com/embed/k6jqx9kZgPM?si=X1Qex5-l4-Ax115d', 219590569, 2022, False, 'contemporary', 'top hits']
['NewJeans (뉴진스) ‘Supernatural’ Official MV (Part.1)', 'HYBE LABELS', 'https://www.youtube.com/embed/ZncbtRo7RXs?si=Irgcwdn0BS1n-TUu', 95814355, 2024, False, 'contemporary', 'top hits']
['Treason', 'Tinashe', 'https://www.youtube.com/embed/m4eVGPN-ZLc?si=3yjcH3yutKxKk9ZG', 556051, 2023, True, 'contemporary', 'well known']
['In For It', 'Tory Lanez', 'https://youtu.be/Amp86v4Nd8Q?si=580Spuf4zjCn2G5S', 59528124, 2018, True, 'contemporary', 'top hits']
['Selfish', 'PnB Rock', '"https://www.youtube.com/embed/u4XyXLQxQbQ?si=ESTBlaXkEa_DGBlu"', 77539193, 2016, True, 'contemporary', 'top hits']
['Cinderella', 'Mac Miller feat Ty Dolla $ign', '"https://www.youtube.com/embed/0fcsGS1dEro?si=_o3cZrrSGLD596Vk"', 36500649, 2016, True, 'contemporary', 'top hits']
['Teyana', 'Tory Lanez', '"https://www.youtube.com/embed/u7v8yEUPilU?si=8qE3xwd66EcxdHVO"', 2171483, 2014, True, 'classic', 'top hits']
['All I Need', 'Lloyd', 'https://youtu.be/15zse5jbU-Q?si=0VnVhlRYG8F14FZW', 8759201, 2014, True, 'classic', 'top hits']
['Put Your Records On', 'Ritt Momney', 'https://www.youtube.com/embed/u7Mf_ZjI2Pg?si=Vyaw-_s1ppGMlV0d', 20994428, 2020, False, 'contemporary', 'top hits']
['Siren', 'Kailee Morgue', 'https://youtu.be/WKWG4zCALoE?si=dDUoXgaku-U9Mc5H', 9322877, 2018, False, 'contemporary', 'top hits']
['MUTT', 'Leon Thomas, Chris Brown', 'https://youtu.be/ueLrb3-oVpY?si=quU91VILvgQtsfZe', 21200039, 2025, False, 'contemporary', 'top hits']
['Mmm Yeah', 'Austin Mahone, Pitpull', 'https://youtu.be/MMAppa1cAVo?si=0aer88WtD37Mjo-P', 257648083, 2014, False, 'classic', 'top hits']
['Cognac Queen', 'Megan Thee Stallion', 'https://youtu.be/GGwVkl56DNo?si=VqWIvEehaP2V_N6l', 32036350, 2022, True, 'contemporary', 'top hits']
['Geeked', 'Lucki', 'https://www.youtube.com/embed/-UO9xzsnPKw?si=gGGXoDPqx4C2y5nY', 4200000, 2019, True, 'contemporary', 'top hits']
['Sunset', 'Lucki', 'https://www.youtube.com/embed/4-pdlpEwMao?si=tNa9_uhxkls_jnR3', 7000000, 2025, True, 'contemporary', 'top hits']
['Randomly', 'Lucki', 'https://www.youtube.com/embed/-UO9xzsnPKw?si=nRVg_Uuaw3A9TUkN', 8000000, 2023, True, 'contemporary', 'top hits']
['LUV', 'Tory Lanez', 'https://www.youtube.com/embed/P9rFeGAdX0A?si=5oJNsXL8rdNXaYA2', 275815687, 2016, False, 'contemporary', 'top hits']
['Nothing like uuuuu', 'Nettspend', 'https://www.youtube.com/embed/2cp_UrFXl0w?si=3dEdpaRIHNJ_2vfe', 1000000, 2024, True, 'contemporary', 'top hits']
['Workin Day and Night', 'Michael Jackson', 'https://www.youtube.com/embed/MWnyCxva6bA?si=xKN1KAaynTbEoP3', 22227316, 1979, False, 'oldie', 'top hits']
['I Wonder', 'Kanye West', 'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l', 165596492, 2007, True, 'classic', 'top hits']
['Goodbye to Love', 'Carpenters', 'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l', 2572645, 1972, False, 'oldie', 'top hits']
['I Will Survive', 'Gloria Gaynor', 'https://www.youtube.com/embed/6dYWe1c3OyU?si=CSVmWbAgI1w-1A2r', 186956675, 1978, False, 'oldie', 'top hits']
['In the Air Tonight', 'Phil Collins', 'https://www.youtube.com/embed/YkADj0TPrJA?si=u5dI2lLLax2zRy9i', 343028265, 1981, True, 'oldie', 'top hits']

### ***CHECKPOINT REACHED!***
Verify that your code is correct with the instructors and discuss the following question:
* Is there any way to make your conditional statements more efficient? Why might this matter?

-----
# **TASK 3: DEFINE FUNCTION FOR CREATING SONG DATABASE**

--

The song_list now must be put into a *Pandas Dataframe* to be used on the website. This is a common Python data format with widespread applications. You don't need to know much about how it works now, your current skills can be used to make the dataframe.

### 3a)

Complete the function for creating the playlist database and the for-loop

In [4]:
''' 3a) DEFINE FUNCTION FOR CREATING PANDAS PLAYLIST '''

# packages
import pandas as pd
import numpy as np

# FILL IN CODE BELOW
# we need to pass song_list as the argument for the function, but use a different variable name
def create_panda_playlist(songs):

    # Create a dataframe for song database
    playlist_df = pd.DataFrame(columns=[
        'title',
        'artists',
        'youtube_url',
        'streams',
        'date_released',
        'explicit',
        'era',
        'popularity'
    ])

    # loop through all songs in LoL and append to pandas dataframe
    for song in songs:
        print(song)
        playlist_df.loc[len(playlist_df)]= song
    
    # display playlist to ensure correctness
    display(playlist_df)
    return playlist_df

### 3b)

Initialize a new variable called *playlist* by calling the create_panda_playlist function

In [5]:
'''3b) CALL FUNCTION TO CREATE PLAYLIST'''

playlist = create_panda_playlist(song_list)

['The Field', 'Blood Orange', 'https://www.youtube.com/embed/yTaz0TB9Zco?si=jUT7iM6EdyZHr-u3', 604906, 2025, False, 'contemporary', 'well known']
['Stupid Prizes', 'redveil', 'https://www.youtube.com/embed/dj5nZsQ3p2o?si=gUrrDWxD-Bk3yThe', 4400, 2025, True, 'contemporary', 'underground']
['Girl, Get Up', 'Doechii, SZA', 'https://www.youtube.com/embed/jBKJbedSrA0?si=R2lDU0OMZmacY3tY', 5100000, 2025, True, 'contemporary', 'top hits']
['Walking Shoes', 'Mali Music', 'https://www.youtube.com/embed/1dexBLGQGSs?si=waNMbE0CHv9s_UeO', 1200000, 2014, False, 'classic', 'top hits']
['Yoga', 'Janelle Monae', 'https://www.youtube.com/embed/0OkB6p_FZAw?si=zMs0gzWyAUTZLrEM"', 83000000, 2015, True, 'contemporary', 'top hits']
['Starboy', 'The Weeknd', 'https://www.youtube.com/embed/Rif-RTvmmss?si=wAMCc-f7WT7rkNNR', 90031660, 2023, True, 'contemporary', 'top hits']
['NINAO', 'Gims', 'https://www.youtube.com/embed/VT2qF97pQNw?si=hkmYaYCt_N0uwwI2', 256000000, 2025, False, 'contemporary', 'top hits']
['Timeless', 'The weeknd & playboi carti', 'https://www.youtube.com/embed/5EpyN_6dqyk?si=_vUSyJSy7Gfz1a97', 263000000, 2025, False, 'contemporary', 'top hits']
['The bigger picture', 'lil baby', 'https://www.youtube.com/embed/_VDGysJGNoI?si=KnGMjHqf-itXkZ7g', 212000000, 2020, False, 'contemporary', 'top hits']
['Diamonds', 'Rihanna', 'https://www.youtube.com/embed/4mVo93E9wpU', 2500000000, 2012, False, 'classic', 'top hits']
['Kill Bill', 'SZA', 'https://www.youtube.com/embed/lcX37Pzobxw', 450000000, 2022, True, 'contemporary', 'top hits']
['CUFF IT', 'Beyoncé', 'https://www.youtube.com/embed/v9o49zO2FfU', 180000000, 2022, True, 'contemporary', 'top hits']
['Blinding Lights', 'The Weeknd', 'https://www.youtube.com/embed/4NRXx6U8ABQ', 800000000, 2019, False, 'contemporary', 'top hits']
['HUMBLE.', 'Kendrick Lamar', 'https://www.youtube.com/embed/tvTRZJ-4EyI', 920000000, 2017, True, 'contemporary', 'top hits']
['Fire Flies', 'Owl City', 'https://www.youtube.com/embed/psuRGfAaju4', 629000000, 2009, False, 'classic', 'top hits']
['So Sick', 'Ne-Yo', 'https://www.youtube.com/embed/IxszlJppRQI', 496000000, 2009, False, 'classic', 'top hits']
['Counting Stars', 'OneRepublic', 'https://www.youtube.com/embed/hT_nvWreIhg', 4400000000, 2013, False, 'classic', 'top hits']
['Flagpole Sitta', 'Harvey Danger', 'https://www.youtube.com/embed/wYsMjEeEg4g?si=JnazjWUphOR8i6CV', 12000000, 2014, False, 'classic', 'top hits']
['Riptide', 'Vance Joy', 'https://www.youtube.com/embed/uJ_1HMAGb4k?si=lpTOfTPMyn7Hn1HK', 739000000, 2013, False, 'classic', 'top hits']
['Dreams and Nightmares', 'Meek Mill', 'https://www.youtube.com/embed/S43S_eMvC-8', 450000000, 2012, True, 'classic', 'top hits']
['Real YN', 'Drake', 'https://www.youtube.com/embed/Lilspazz9_RealYN', 677000, 2023, False, 'contemporary', 'well known']
['Drip Too Hard', 'Lil Baby', 'https://www.youtube.com/embed/uTRJ-S66m6g', 1200000000, 2018, True, 'contemporary', 'top hits']
['Nights', 'Frank Ocean', 'https://www.youtube.com/embed/r4l9bFqgMaQ', 350000000, 2016, True, 'contemporary', 'top hits']
['PARTYNEXTDOOR', 'PARTYNEXTDOOR', 'https://www.youtube.com/embed/example', 150000000, 2020, True, 'contemporary', 'top hits']
['20 Plus', 'Lilspazz9', 'https://www.youtube.com/embed/n3-QbOpwEIY?si=9H8EQiqrNfqfBrxn', 1987178, 2025, True, 'contemporary', 'top hits']
['Vultures', 'FullyChop', 'https://www.youtube.com/embed/FdzPyCJpl_A?si=E0jZqKfHUyAIty6j', 1128409, 2026, True, 'contemporary', 'top hits']
['Ian mean it shot by drevegas', 'imsomarcus', 'https://www.youtube.com/embed/ILNT1ZYr3oE?si=iu38ILi45FNnT8av', 16901, 2025, True, 'contemporary', 'underground']
["While We're Young", 'Jhené Aiko', 'https://www.youtube.com/embed/LjvwRSKVQNs?si=ulvauqMsxdnjWzIF', 106554052, 2017, True, 'contemporary', 'top hits']
['LOYALTY', 'Kendrick Lamar', 'https://www.youtube.com/embed/sN8H2ypmzlA?si=wYFaQDitA-_Heo24', 1763334, 2018, True, 'contemporary', 'top hits']
['KiLLKiSS', 'Ave Mujica', 'https://www.youtube.com/embed/RexyoaXaQ1o?si=wyHbFJSAVq17t-8w', 6923624, 2025, False, 'contemporary', 'top hits']
['TWICE"Talk that Talk" M/V', 'TWICE', 'https://www.youtube.com/embed/k6jqx9kZgPM?si=X1Qex5-l4-Ax115d', 219590569, 2022, False, 'contemporary', 'top hits']
['NewJeans (뉴진스) ‘Supernatural’ Official MV (Part.1)', 'HYBE LABELS', 'https://www.youtube.com/embed/ZncbtRo7RXs?si=Irgcwdn0BS1n-TUu', 95814355, 2024, False, 'contemporary', 'top hits']
['Treason', 'Tinashe', 'https://www.youtube.com/embed/m4eVGPN-ZLc?si=3yjcH3yutKxKk9ZG', 556051, 2023, True, 'contemporary', 'well known']
['In For It', 'Tory Lanez', 'https://youtu.be/Amp86v4Nd8Q?si=580Spuf4zjCn2G5S', 59528124, 2018, True, 'contemporary', 'top hits']
['Selfish', 'PnB Rock', '"https://www.youtube.com/embed/u4XyXLQxQbQ?si=ESTBlaXkEa_DGBlu"', 77539193, 2016, True, 'contemporary', 'top hits']
['Cinderella', 'Mac Miller feat Ty Dolla $ign', '"https://www.youtube.com/embed/0fcsGS1dEro?si=_o3cZrrSGLD596Vk"', 36500649, 2016, True, 'contemporary', 'top hits']
['Teyana', 'Tory Lanez', '"https://www.youtube.com/embed/u7v8yEUPilU?si=8qE3xwd66EcxdHVO"', 2171483, 2014, True, 'classic', 'top hits']
['All I Need', 'Lloyd', 'https://youtu.be/15zse5jbU-Q?si=0VnVhlRYG8F14FZW', 8759201, 2014, True, 'classic', 'top hits']
['Put Your Records On', 'Ritt Momney', 'https://www.youtube.com/embed/u7Mf_ZjI2Pg?si=Vyaw-_s1ppGMlV0d', 20994428, 2020, False, 'contemporary', 'top hits']
['Siren', 'Kailee Morgue', 'https://youtu.be/WKWG4zCALoE?si=dDUoXgaku-U9Mc5H', 9322877, 2018, False, 'contemporary', 'top hits']
['MUTT', 'Leon Thomas, Chris Brown', 'https://youtu.be/ueLrb3-oVpY?si=quU91VILvgQtsfZe', 21200039, 2025, False, 'contemporary', 'top hits']
['Mmm Yeah', 'Austin Mahone, Pitpull', 'https://youtu.be/MMAppa1cAVo?si=0aer88WtD37Mjo-P', 257648083, 2014, False, 'classic', 'top hits']
['Cognac Queen', 'Megan Thee Stallion', 'https://youtu.be/GGwVkl56DNo?si=VqWIvEehaP2V_N6l', 32036350, 2022, True, 'contemporary', 'top hits']
['Geeked', 'Lucki', 'https://www.youtube.com/embed/-UO9xzsnPKw?si=gGGXoDPqx4C2y5nY', 4200000, 2019, True, 'contemporary', 'top hits']
['Sunset', 'Lucki', 'https://www.youtube.com/embed/4-pdlpEwMao?si=tNa9_uhxkls_jnR3', 7000000, 2025, True, 'contemporary', 'top hits']
['Randomly', 'Lucki', 'https://www.youtube.com/embed/-UO9xzsnPKw?si=nRVg_Uuaw3A9TUkN', 8000000, 2023, True, 'contemporary', 'top hits']
['LUV', 'Tory Lanez', 'https://www.youtube.com/embed/P9rFeGAdX0A?si=5oJNsXL8rdNXaYA2', 275815687, 2016, False, 'contemporary', 'top hits']
['Nothing like uuuuu', 'Nettspend', 'https://www.youtube.com/embed/2cp_UrFXl0w?si=3dEdpaRIHNJ_2vfe', 1000000, 2024, True, 'contemporary', 'top hits']
['Workin Day and Night', 'Michael Jackson', 'https://www.youtube.com/embed/MWnyCxva6bA?si=xKN1KAaynTbEoP3', 22227316, 1979, False, 'oldie', 'top hits']
['I Wonder', 'Kanye West', 'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l', 165596492, 2007, True, 'classic', 'top hits']
['Goodbye to Love', 'Carpenters', 'https://www.youtube.com/embed/MxEjnYdfLXU?si=VWGOZajPTQRrAi1l', 2572645, 1972, False, 'oldie', 'top hits']
['I Will Survive', 'Gloria Gaynor', 'https://www.youtube.com/embed/6dYWe1c3OyU?si=CSVmWbAgI1w-1A2r', 186956675, 1978, False, 'oldie', 'top hits']
['In the Air Tonight', 'Phil Collins', 'https://www.youtube.com/embed/YkADj0TPrJA?si=u5dI2lLLax2zRy9i', 343028265, 1981, True, 'oldie', 'top hits']

,title,artists,youtube_url,streams,date_released,explicit,era,popularity
0,The Field,Blood Orange,https://www.youtube.com/embed/yTaz0TB9Zco?si=j...,604906,2025,False,contemporary,well known
1,Stupid Prizes,redveil,https://www.youtube.com/embed/dj5nZsQ3p2o?si=g...,4400,2025,True,contemporary,underground
2,"Girl, Get Up","Doechii, SZA",https://www.youtube.com/embed/jBKJbedSrA0?si=R...,5100000,2025,True,contemporary,top hits
3,Walking Shoes,Mali Music,https://www.youtube.com/embed/1dexBLGQGSs?si=w...,1200000,2014,False,classic,top hits
4,Yoga,Janelle Monae,https://www.youtube.com/embed/0OkB6p_FZAw?si=z...,83000000,2015,True,contemporary,top hits
5,Starboy,The Weeknd,https://www.youtube.com/embed/Rif-RTvmmss?si=w...,90031660,2023,True,contemporary,top hits
6,NINAO,Gims,https://www.youtube.com/embed/VT2qF97pQNw?si=h...,256000000,2025,False,contemporary,top hits
7,Timeless,The weeknd & playboi carti,https://www.youtube.com/embed/5EpyN_6dqyk?si=_...,263000000,2025,False,contemporary,top hits
8,The bigger picture,lil baby,https://www.youtube.com/embed/_VDGysJGNoI?si=K...,212000000,2020,False,contemporary,top hits
9,Diamonds,Rihanna,https://www.youtube.com/embed/4mVo93E9wpU,2500000000,2012,False,classic,top hits
10,Kill Bill,SZA,https://www.youtube.com/embed/lcX37Pzobxw,450000000,2022,True,contemporary,top hits
11,CUFF IT,Beyoncé,https://www.youtube.com/embed/v9o49zO2FfU,180000000,2022,True,contemporary,top hits
12,Blinding Lights,The Weeknd,https://www.youtube.com/embed/4NRXx6U8ABQ,800000000,2019,False,contemporary,top hits
13,HUMBLE.,Kendrick Lamar,https://www.youtube.com/embed/tvTRZJ-4EyI,920000000,2017,True,contemporary,top hits
14,Fire Flies,Owl City,https://www.youtube.com/embed/psuRGfAaju4,629000000,2009,False,classic,top hits
15,So Sick,Ne-Yo,https://www.youtube.com/embed/IxszlJppRQI,496000000,2009,False,classic,top hits
16,Counting Stars,OneRepublic,https://www.youtube.com/embed/hT_nvWreIhg,4400000000,2013,False,classic,top hits
17,Flagpole Sitta,Harvey Danger,https://www.youtube.com/embed/wYsMjEeEg4g?si=J...,12000000,2014,False,classic,top hits
18,Riptide,Vance Joy,https://www.youtube.com/embed/uJ_1HMAGb4k?si=l...,739000000,2013,False,classic,top hits
19,Dreams and Nightmares,Meek Mill,https://www.youtube.com/embed/S43S_eMvC-8,450000000,2012,True,classic,top hits
20,Real YN,Drake,https://www.youtube.com/embed/Lilspazz9_RealYN,677000,2023,False,contemporary,well known
21,Drip Too Hard,Lil Baby,https://www.youtube.com/embed/uTRJ-S66m6g,1200000000,2018,True,contemporary,top hits
22,Nights,Frank Ocean,https://www.youtube.com/embed/r4l9bFqgMaQ,350000000,2016,True,contemporary,top hits
23,PARTYNEXTDOOR,PARTYNEXTDOOR,https://www.youtube.com/embed/example,150000000,2020,True,contemporary,top hits
24,20 Plus,Lilspazz9,https://www.youtube.com/embed/n3-QbOpwEIY?si=9...,1987178,2025,True,contemporary,top hits
25,Vultures,FullyChop,https://www.youtube.com/embed/FdzPyCJpl_A?si=E...,1128409,2026,True,contemporary,top hits
26,Ian mean it shot by drevegas,imsomarcus,https://www.youtube.com/embed/ILNT1ZYr3oE?si=i...,16901,2025,True,contemporary,underground
27,While We're Young,Jhené Aiko,https://www.youtube.com/embed/LjvwRSKVQNs?si=u...,106554052,2017,True,contemporary,top hits
28,LOYALTY,Kendrick Lamar,https://www.youtube.com/embed/sN8H2ypmzlA?si=w...,1763334,2018,True,contemporary,top hits
29,KiLLKiSS,Ave Mujica,https://www.youtube.com/embed/RexyoaXaQ1o?si=w...,6923624,2025,False,contemporary,top hits
30,"TWICE""Talk that Talk"" M/V",TWICE,https://www.youtube.com/embed/k6jqx9kZgPM?si=X...,219590569,2022,False,contemporary,top hits
31,NewJeans (뉴진스) ‘Supernatural’ Official MV (Par...,HYBE LABELS,https://www.youtube.com/embed/ZncbtRo7RXs?si=I...,95814355,2024,False,contemporary,top hits
32,Treason,Tinashe,https://www.youtube.com/embed/m4eVGPN-ZLc?si=3...,556051,2023,True,contemporary,well known
33,In For It,Tory Lanez,https://youtu.be/Amp86v4Nd8Q?si=580Spuf4zjCn2G5S,59528124,2018,True,contemporary,top hits
34,Selfish,PnB Rock,"""https://www.youtube.com/embed/u4XyXLQxQbQ?si=...",77539193,2016,True,contemporary,top hits
35,Cinderella,Mac Miller feat Ty Dolla $ign,"""https://www.youtube.com/embed/0fcsGS1dEro?si=...",36500649,2016,True,contemporary,top hits
36,Teyana,Tory Lanez,"""https://www.youtube.com/embed/u7v8yEUPilU?si=...",2171483,2014,True,classic,top hits
37,All I Need,Lloyd,https://youtu.be/15zse5jbU-Q?si=0VnVhlRYG8F14FZW,8759201,2014,True,classic,top hits
38,Put Your Records On,Ritt Momney,https://www.youtube.com/embed/u7Mf_ZjI2Pg?si=V...,20994428,2020,False,contemporary,top hits
39,Siren,Kailee Morgue,https://youtu.be/WKWG4zCALoE?si=dDUoXgaku-U9Mc5H,9322877,2018,False,contemporary,top hits
40,MUTT,"Leon Thomas, Chris Brown",https://youtu.be/ueLrb3-oVpY?si=quU91VILvgQtsfZe,21200039,2025,False,contemporary,top hits
41,Mmm Yeah,"Austin Mahone, Pitpull",https://youtu.be/MMAppa1cAVo?si=0aer88WtD37Mjo-P,257648083,2014,False,classic,top hits
42,Cognac Queen,Megan Thee Stallion,https://youtu.be/GGwVkl56DNo?si=VqWIvEehaP2V_N6l,32036350,2022,True,contemporary,top hits
43,Geeked,Lucki,https://www.youtube.com/embed/-UO9xzsnPKw?si=g...,4200000,2019,True,contemporary,top hits
44,Sunset,Lucki,https://www.youtube.com/embed/4-pdlpEwMao?si=t...,7000000,2025,True,contemporary,top hits
45,Randomly,Lucki,https://www.youtube.com/embed/-UO9xzsnPKw?si=n...,8000000,2023,True,contemporary,top hits
46,LUV,Tory Lanez,https://www.youtube.com/embed/P9rFeGAdX0A?si=5...,275815687,2016,False,contemporary,top hits
47,Nothing like uuuuu,Nettspend,https://www.youtube.com/embed/2cp_UrFXl0w?si=3...,1000000,2024,True,contemporary,top hits
48,Workin Day and Night,Michael Jackson,https://www.youtube.com/embed/MWnyCxva6bA?si=x...,22227316,1979,False,oldie,top hits
49,I Wonder,Kanye West,https://www.youtube.com/embed/MxEjnYdfLXU?si=V...,165596492,2007,True,classic,top hits
50,Goodbye to Love,Carpenters,https://www.youtube.com/embed/MxEjnYdfLXU?si=V...,2572645,1972,False,oldie,top hits
51,I Will Survive,Gloria Gaynor,https://www.youtube.com/embed/6dYWe1c3OyU?si=C...,186956675,1978,False,oldie,top hits
52,In the Air Tonight,Phil Collins,https://www.youtube.com/embed/YkADj0TPrJA?si=u...,343028265,1981,True,oldie,top hits

### ***CHECKPOINT REACHED!***
Verify that your code is correct with the instructors and discuss the following questions:
* How many dimensions are in the playlist now?

-----
# **TASK 4: CALL PANDAS FUNCTIONS FOR ORGANIZING PLAYLIST**

--

Lastly, the playlist needs to be ordered alphabetically by song titles. There's a function we can use to do this called *sort*.

In [6]:
''' 4) SORT PLAYLIST ALPHABETICALLY '''

# FILL IN CODE BELOW
# hint: you need to put the column name for the values to be sorted
playlist.sort_values('title', inplace=True)

# print to ensure correctness
playlist.reset_index(drop=True, inplace=True)
display(playlist)

,title,artists,youtube_url,streams,date_released,explicit,era,popularity
0,20 Plus,Lilspazz9,https://www.youtube.com/embed/n3-QbOpwEIY?si=9...,1987178,2025,True,contemporary,top hits
1,All I Need,Lloyd,https://youtu.be/15zse5jbU-Q?si=0VnVhlRYG8F14FZW,8759201,2014,True,classic,top hits
2,Blinding Lights,The Weeknd,https://www.youtube.com/embed/4NRXx6U8ABQ,800000000,2019,False,contemporary,top hits
3,CUFF IT,Beyoncé,https://www.youtube.com/embed/v9o49zO2FfU,180000000,2022,True,contemporary,top hits
4,Cinderella,Mac Miller feat Ty Dolla $ign,"""https://www.youtube.com/embed/0fcsGS1dEro?si=...",36500649,2016,True,contemporary,top hits
5,Cognac Queen,Megan Thee Stallion,https://youtu.be/GGwVkl56DNo?si=VqWIvEehaP2V_N6l,32036350,2022,True,contemporary,top hits
6,Counting Stars,OneRepublic,https://www.youtube.com/embed/hT_nvWreIhg,4400000000,2013,False,classic,top hits
7,Diamonds,Rihanna,https://www.youtube.com/embed/4mVo93E9wpU,2500000000,2012,False,classic,top hits
8,Dreams and Nightmares,Meek Mill,https://www.youtube.com/embed/S43S_eMvC-8,450000000,2012,True,classic,top hits
9,Drip Too Hard,Lil Baby,https://www.youtube.com/embed/uTRJ-S66m6g,1200000000,2018,True,contemporary,top hits
10,Fire Flies,Owl City,https://www.youtube.com/embed/psuRGfAaju4,629000000,2009,False,classic,top hits
11,Flagpole Sitta,Harvey Danger,https://www.youtube.com/embed/wYsMjEeEg4g?si=J...,12000000,2014,False,classic,top hits
12,Geeked,Lucki,https://www.youtube.com/embed/-UO9xzsnPKw?si=g...,4200000,2019,True,contemporary,top hits
13,"Girl, Get Up","Doechii, SZA",https://www.youtube.com/embed/jBKJbedSrA0?si=R...,5100000,2025,True,contemporary,top hits
14,Goodbye to Love,Carpenters,https://www.youtube.com/embed/MxEjnYdfLXU?si=V...,2572645,1972,False,oldie,top hits
15,HUMBLE.,Kendrick Lamar,https://www.youtube.com/embed/tvTRZJ-4EyI,920000000,2017,True,contemporary,top hits
16,I Will Survive,Gloria Gaynor,https://www.youtube.com/embed/6dYWe1c3OyU?si=C...,186956675,1978,False,oldie,top hits
17,I Wonder,Kanye West,https://www.youtube.com/embed/MxEjnYdfLXU?si=V...,165596492,2007,True,classic,top hits
18,Ian mean it shot by drevegas,imsomarcus,https://www.youtube.com/embed/ILNT1ZYr3oE?si=i...,16901,2025,True,contemporary,underground
19,In For It,Tory Lanez,https://youtu.be/Amp86v4Nd8Q?si=580Spuf4zjCn2G5S,59528124,2018,True,contemporary,top hits
20,In the Air Tonight,Phil Collins,https://www.youtube.com/embed/YkADj0TPrJA?si=u...,343028265,1981,True,oldie,top hits
21,KiLLKiSS,Ave Mujica,https://www.youtube.com/embed/RexyoaXaQ1o?si=w...,6923624,2025,False,contemporary,top hits
22,Kill Bill,SZA,https://www.youtube.com/embed/lcX37Pzobxw,450000000,2022,True,contemporary,top hits
23,LOYALTY,Kendrick Lamar,https://www.youtube.com/embed/sN8H2ypmzlA?si=w...,1763334,2018,True,contemporary,top hits
24,LUV,Tory Lanez,https://www.youtube.com/embed/P9rFeGAdX0A?si=5...,275815687,2016,False,contemporary,top hits
25,MUTT,"Leon Thomas, Chris Brown",https://youtu.be/ueLrb3-oVpY?si=quU91VILvgQtsfZe,21200039,2025,False,contemporary,top hits
26,Mmm Yeah,"Austin Mahone, Pitpull",https://youtu.be/MMAppa1cAVo?si=0aer88WtD37Mjo-P,257648083,2014,False,classic,top hits
27,NINAO,Gims,https://www.youtube.com/embed/VT2qF97pQNw?si=h...,256000000,2025,False,contemporary,top hits
28,NewJeans (뉴진스) ‘Supernatural’ Official MV (Par...,HYBE LABELS,https://www.youtube.com/embed/ZncbtRo7RXs?si=I...,95814355,2024,False,contemporary,top hits
29,Nights,Frank Ocean,https://www.youtube.com/embed/r4l9bFqgMaQ,350000000,2016,True,contemporary,top hits
30,Nothing like uuuuu,Nettspend,https://www.youtube.com/embed/2cp_UrFXl0w?si=3...,1000000,2024,True,contemporary,top hits
31,PARTYNEXTDOOR,PARTYNEXTDOOR,https://www.youtube.com/embed/example,150000000,2020,True,contemporary,top hits
32,Put Your Records On,Ritt Momney,https://www.youtube.com/embed/u7Mf_ZjI2Pg?si=V...,20994428,2020,False,contemporary,top hits
33,Randomly,Lucki,https://www.youtube.com/embed/-UO9xzsnPKw?si=n...,8000000,2023,True,contemporary,top hits
34,Real YN,Drake,https://www.youtube.com/embed/Lilspazz9_RealYN,677000,2023,False,contemporary,well known
35,Riptide,Vance Joy,https://www.youtube.com/embed/uJ_1HMAGb4k?si=l...,739000000,2013,False,classic,top hits
36,Selfish,PnB Rock,"""https://www.youtube.com/embed/u4XyXLQxQbQ?si=...",77539193,2016,True,contemporary,top hits
37,Siren,Kailee Morgue,https://youtu.be/WKWG4zCALoE?si=dDUoXgaku-U9Mc5H,9322877,2018,False,contemporary,top hits
38,So Sick,Ne-Yo,https://www.youtube.com/embed/IxszlJppRQI,496000000,2009,False,classic,top hits
39,Starboy,The Weeknd,https://www.youtube.com/embed/Rif-RTvmmss?si=w...,90031660,2023,True,contemporary,top hits
40,Stupid Prizes,redveil,https://www.youtube.com/embed/dj5nZsQ3p2o?si=g...,4400,2025,True,contemporary,underground
41,Sunset,Lucki,https://www.youtube.com/embed/4-pdlpEwMao?si=t...,7000000,2025,True,contemporary,top hits
42,"TWICE""Talk that Talk"" M/V",TWICE,https://www.youtube.com/embed/k6jqx9kZgPM?si=X...,219590569,2022,False,contemporary,top hits
43,Teyana,Tory Lanez,"""https://www.youtube.com/embed/u7v8yEUPilU?si=...",2171483,2014,True,classic,top hits
44,The Field,Blood Orange,https://www.youtube.com/embed/yTaz0TB9Zco?si=j...,604906,2025,False,contemporary,well known
45,The bigger picture,lil baby,https://www.youtube.com/embed/_VDGysJGNoI?si=K...,212000000,2020,False,contemporary,top hits
46,Timeless,The weeknd & playboi carti,https://www.youtube.com/embed/5EpyN_6dqyk?si=_...,263000000,2025,False,contemporary,top hits
47,Treason,Tinashe,https://www.youtube.com/embed/m4eVGPN-ZLc?si=3...,556051,2023,True,contemporary,well known
48,Vultures,FullyChop,https://www.youtube.com/embed/FdzPyCJpl_A?si=E...,1128409,2026,True,contemporary,top hits
49,Walking Shoes,Mali Music,https://www.youtube.com/embed/1dexBLGQGSs?si=w...,1200000,2014,False,classic,top hits
50,While We're Young,Jhené Aiko,https://www.youtube.com/embed/LjvwRSKVQNs?si=u...,106554052,2017,True,contemporary,top hits
51,Workin Day and Night,Michael Jackson,https://www.youtube.com/embed/MWnyCxva6bA?si=x...,22227316,1979,False,oldie,top hits
52,Yoga,Janelle Monae,https://www.youtube.com/embed/0OkB6p_FZAw?si=z...,83000000,2015,True,contemporary,top hits

### ***CHECKPOINT REACHED!***
Verify that your code is correct with the instructors and discuss the following questions:
* If the LoL and playlist are 2D data structures, what would three dimensional data look like?
* Would you add/change anything to the playlist database or the website?

----
# **FINAL TASK: READ, RESPOND, SUBMIT**

--

A) Read this article from Michael Coard, leader of the ATAC: https://www.inquirer.com/opinion/commentary/semiquincentennial-trump-presidents-house-national-park-service-20260705.html?id=cPAHFvvrq4eZ3&utm_source=social&utm_campaign=gift_link&utm_medium=referral

B) Write 2-5 sentence responses to the following questions:
* Why did you choose these songs?
* Did you learn anything new in this article?
* What is Michael Coard's main profession? What does someone with that job do?

C) Submit this completed file and written responses to Google Classroom

-----

In [10]:
# remove explicit songs for posting on web
playlist_nonexplicit = playlist[playlist["explicit"] == False].copy()

In [11]:
import json

playlist_nonexplicit.to_json('songs_data.json', orient='records', indent=2)
print("✅ Songs data exported to songs_data.json")

✅ Songs data exported to songs_data.json

In [12]:
import re

# Read the JSON file
with open('songs_data.json', 'r', encoding='utf-8') as f:
    json_data = f.read()

# Read the HTML file
with open('index.html', 'r', encoding='utf-8') as f:
    html_content = f.read()

# Replace the old songs array only if it exists
pattern = r'const songs = \[.*?\];'

if re.search(pattern, html_content, flags=re.DOTALL):
    updated_html = re.sub(
        pattern,
        lambda match: f'const songs = {json_data};',
        html_content,
        flags=re.DOTALL,
    )

    with open('index.html', 'w', encoding='utf-8') as f:
        f.write(updated_html)

    print('✅ HTML playlist updated with latest songs!')
else:
    print('No matching songs array found in index.html. The page loads songs from songs_data.json, so no update was needed.')

No matching songs array found in index.html. The page loads songs from songs_data.json, so no update was needed.